services:
  server:
    image: keuzewijzer-server
    build:
      context: ./Api
      dockerfile: Dockerfile
    expose:
      - "8080"
      - "8081"
    environment:
      ASPNETCORE_ENVIRONMENT: $${{ vars.ASPNETCORE_ENVIRONMENT }}
      DB_CONNECTION_STRING: host=$${{ vars.DB_HOST }};port=1433;database=$${{ vars.DB_NAME }};username=$${{ secrets.DB_USER }};password=$${{ secrets.DB_PASSWORD }}
    networks:
      - container_network
      
networks:
  container_network:
    name: $${{ vars.ENV_KEY }}_network
    external: true
