services:
  server:
    image: keuzewijzer-server
    build:
      context: ./Api
      dockerfile: Dockerfile
    expose:
      - "8080"
      - "8081"
    environment:
      ASPNETCORE_ENVIRONMENT: ${{ env.ASPNETCORE_ENVIRONMENT }}
      DB_CONNECTION_STRING: host=${{ env.DB_HOST }};port=1433;database=${{ env.DB_NAME }};username=${{ secrets.DB_USER }};password=${{ secrets.DB_PASSWORD }}
    networks:
      - container_network
      
networks:
  container_network:
    name: ${{ env.ENV_KEY }}_network
    external: true
