services:
  api:
    image: keuzewijzer-api:${ENV_KEY}
    build:
      context: ./
      dockerfile: DockerfileApi
      args:
        ENV_KEY: ${ENV_KEY}
        DB_CONNECTION_STRING: "Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};Encrypt=True;TrustServerCertificate=True"
    ports:
      - "${API_PORT}:8080"
    volumes:
      - ./KeuzeWijzerCore.dll:/app/KeuzeWijzerCore.dll:r
    environment:
      AZUREAD__CLIENTSECRET: ${AZUREAD_CLIENTSECRET}
      SENDGRID_KEY: ${SENDGRID_KEY}
      ASPNETCORE_HTTP_PORTS: "8080"
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      DB_CONNECTION_STRING: "Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};Encrypt=True;TrustServerCertificate=True"
    networks:
      - container_network

  mvc:
    image: keuzewijzer-mvc:${ENV_KEY}
    build:
      context: ./
      dockerfile: DockerfileMvc
    ports:
      - "${MVC_PORT}:8082"
    environment:
      # Use the internal container port!
      ApiUri: "http://${ENV_KEY}-server-api-1:8080"
      ASPNETCORE_HTTP_PORTS: "8082"
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
    networks:
      - container_network

networks:
  container_network:
    name: ${ENV_KEY}_network
    external: true
