services:
  server:
    environment:
      ASPNETCORE_ENVIRONMENT: development
      DB_CONNECTION_STRING: $${{ secrets.DB_CONNECTION_STRING_DEV }}
    networks:
      - dev_network

networks:
  dev_network:
    external: true
