services:
  server:
    image: keuzewijzer-server
    build:
      context: ./Api
      dockerfile: Dockerfile
    expose:
      - "8080"
      - "8081"
    environment:
      ASPNETCORE_ENVIRONMENT: $${{ ASPNETCORE_ENVIRONMENT }}
      DB_CONNECTION_STRING: host=$${{ DB_HOST }};port=1433;database=$${{ DB_NAME }};username=$${{ secrets.DB_USER }};password=$${{ secrets.DB_PASSWORD }}
    networks:
      container_network: $${{ ENV_KEY }}_network

networks:
  container_network:
    external: true
