// <auto-generated />
using System;
using KeuzeWijzerApi.DAL.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KeuzeWijzerApi.Migrations
{
    [DbContext(typeof(KeuzeWijzerContext))]
    [Migration("20240417190355_ini")]
    partial class ini
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("KeuzeWijzerApi.Models.LearningRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Leerroutes");
                });

            modelBuilder.Entity("KeuzeWijzerApi.Models.LearningYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LearningRouteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LearningRouteId");

                    b.ToTable("LearningYears");
                });

            modelBuilder.Entity("KeuzeWijzerApi.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("KeuzeWijzerApi.Models.Semester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LearningYearId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LearningYearId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LearningYearId");

                    b.HasIndex("LearningYearId1");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("KeuzeWijzerApi.Models.SemesterModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SemesterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("SemesterId");

                    b.ToTable("SemesterModules");
                });

            modelBuilder.Entity("KeuzeWijzerApi.Models.LearningYear", b =>
                {
                    b.HasOne("KeuzeWijzerApi.Models.LearningRoute", null)
                        .WithMany("LearningYears")
                        .HasForeignKey("LearningRouteId");
                });

            modelBuilder.Entity("KeuzeWijzerApi.Models.Semester", b =>
                {
                    b.HasOne("KeuzeWijzerApi.Models.LearningYear", null)
                        .WithMany("FirstSemester")
                        .HasForeignKey("LearningYearId");

                    b.HasOne("KeuzeWijzerApi.Models.LearningYear", null)
                        .WithMany("SecondSemester")
                        .HasForeignKey("LearningYearId1");
                });

            modelBuilder.Entity("KeuzeWijzerApi.Models.SemesterModule", b =>
                {
                    b.HasOne("KeuzeWijzerApi.Models.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId");

                    b.HasOne("KeuzeWijzerApi.Models.Semester", "Semester")
                        .WithMany("SemesterModules")
                        .HasForeignKey("SemesterId");

                    b.Navigation("Module");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("KeuzeWijzerApi.Models.LearningRoute", b =>
                {
                    b.Navigation("LearningYears");
                });

            modelBuilder.Entity("KeuzeWijzerApi.Models.LearningYear", b =>
                {
                    b.Navigation("FirstSemester");

                    b.Navigation("SecondSemester");
                });

            modelBuilder.Entity("KeuzeWijzerApi.Models.Semester", b =>
                {
                    b.Navigation("SemesterModules");
                });
#pragma warning restore 612, 618
        }
    }
}
